google_chrome__yum_proxy: "http://brick.carrier.duckdns.org:3142"

nspawn_on_fedora__machines_directory: "/home/nspawn"

# roles/debian_on_nspawn
# Note: I don't know if this is the recommended way for Ubuntu
locale_gen:
  - en_GB.UTF-8

# Update our master copy of the RPMFusion keys from the target system.
# This should sound worrying!  The role contains one fragile mitigation:
# the update is also reported as a failure.
rpmfusion__update_master_keys: yes
