users:
 - name: alan-sysop
   full_name: Alan Jenkins (system admin)
   admin: True

 - name: alan-test
   full_name: Alan Jenkins

# We can do this the hard way, or the easy way.
test_servers__admins:
 - alan-sysop

# We don't assign the systemd-journal group in role/users,
# to avoid that mysteriously depending on roles/nspawn-on-debian
# (that's what installs systemd).
systemd_journal__users: "{{ test_servers__admins }}"

sshkeys: "{{ inventory_dir }}/files/ssh-authkeys/"
openssh_server__authkeys:
  - name: alan-sysop
    sshkey: "{{ lookup('file', sshkeys + 'alan-sysop') }}"

jenkins_shared__users:
 - alan

# Server
daily_rsync__dir: "/data/network-backup"

# Client
daily_rsync__server: "{{ inventory_hostname }}"
daily_rsync__server_addresses:
 - "invalid"
 - "{{ inventory_hostname }}"

# Debian 10: every lvm command complains about USB SD card reader,
# causing cron mail.  Fixed in Debian 11 (but not Ubuntu 20.04).
daily_rsync__prepare_script: !unsafe |
  #!/bin/bash
  set -u -o pipefail
  lvm_vg=vg_virt
  lvm_lv=root

  l_quiet() {
    LC_ALL=C "$@" 2>&1 1>/dev/null | ( grep -v "open failed: No medium found$" || true )
  }
  mkdir -p /ansible-managed/daily-rsync/snapshot &&
  chmod o-rwx /ansible-managed/daily-rsync/snapshot &&
  l_quiet lvcreate -s -n daily-rsync-snap -L 1G "/dev/${lvm_vg}/${lvm_lv}" &&
  mount "/dev/${lvm_vg}/daily-rsync-snap" /ansible-managed/daily-rsync/snapshot

daily_rsync__cleanup_script: !unsafe |
  #!/bin/bash
  set -u -o pipefail
  lvm_vg=vg_virt

  l_quiet() {
        LC_ALL=C "$@" 2>&1 1>/dev/null | ( grep -v "open failed: No medium found$" || true )
  }
  if findmnt /ansible-managed/daily-rsync/snapshot >/dev/null; then
    umount /ansible-managed/daily-rsync/snapshot
  fi
  if [ -e "/dev/${lvm_vg}/daily-rsync-snap" ]; then
    l_quiet lvremove -y "/dev/${lvm_vg}/daily-rsync-snap"
  fi

daily_rsync__backups:
  - directory: "/ansible-managed/daily-rsync/snapshot/home/alan"
    name: alan

  - directory: "/ansible-managed/daily-rsync/snapshot/home/.shared-internal"
    name: jenkins-shared

  - directory: "/ansible-managed/daily-rsync/snapshot/home/.shared-separate-internal/Photos"
    name: jenkins-photos

  # jenkins-music is not included here
