users:
 - name: alan-sysop
   full_name: Alan Jenkins (system admin)
   admin: True

 - name: alan-test
   full_name: Alan Jenkins

# We can do this the hard way, or the easy way.
test_servers__admins:
 - alan-sysop

# We don't assign the systemd-journal group in role/users,
# to avoid that mysteriously depending on roles/nspawn-on-debian
# (that's what installs systemd).
systemd_journal__users: "{{ test_servers__admins }}"

test_servers__sshkeys: "{{ inventory_dir }}/files/ssh-authkeys/"
openssh_server__authkeys:
  - name: alan-sysop
    sshkey: "{{ lookup('file', test_servers__sshkeys + 'alan-sysop') }}"

jenkins_photos__users:
 - alan

daily_rsync__server: "debian10-vm"
daily_rsync__server_addresses:
 - "invalid"
 - "debian10-vm"
daily_rsync__dir: "/data/rdiff-backup"
