# I don't like updatedb running as a scheduled task.
# It's maybe less likely to be a problem than it used to be
# (mlocate optimization).  But I don't use it, so it's simplest to remove.

# Remove the package carefully, aborting on dependents.
# Wish this was cleaner, but it's not supported by Ansible apt module.
# import_role would make this nicer, but it requires Ansible 2.4.0.

# 1/3) Query condition
- name: query  | is mlocate installed?
  script: scripts/dpkg-state mlocate
  register: mlocate__prev_dpkg_state
  failed_when: mlocate__prev_dpkg_state.rc != 0
  check_mode: False
  changed_when: False

# 2/3) Run command task conditionally, to provide accurate "changed" status
- name: ensure | mlocate is removed, including config files
  # Full removal including config files (avoid stale /etc/cron.daily/mlocate).
  # (Without this we would also have to accept state "config-files")
  command: dpkg --purge mlocate
  when: mlocate__prev_dpkg_state.stdout|trim != "not-installed"
  args:
    # Can't use ansible apt module.  It would remove packages which depend
    # on mlocate, without prompting.
    warn: no

# 3/3) The condition must now hold.  This "fixes" ansible check mode.
- name: check  | mlocate is not installed
  script: scripts/dpkg-state mlocate
  register: mlocate__dpkg_state
  failed_when: mlocate__dpkg_state.stdout|trim != "not-installed"
  check_mode: False
  changed_when: False

- name: Remove unused packages (apt autoremove)
  command: apt-get autoremove
  args:
    warn: no  # can't use apt module, because this task crashes (Ansible 2.2.1.0).
