galaxy_info:
  author: Alan Jenkins
  description: Install and enable atop monitoring service

  license: GPLv3

  # Ansible version without known vulnerabilities, according to debops project
  min_ansible_version: 2.1.4.0

  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
