- name: Install icinga2
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2

    # check_dig in monitoring-plugins-standard, which is only recommended.
    #
    # This will also pull in rpcbind :(.
    # Hence roles/remove-rpcbind, which masks it in advance.
    - monitoring-plugins


# Note this role does not enable any "features", including the checker (?).
# The output features you want differ completely, between
# icinga2-classicui and the "modern" Icinga Web frontends.
# (Even the logs of old states are different plugins).


# We attempt in vain to mitigate dpkg prompts on upgrade.
# We leave the example conf.d/ alone and create our own.
# See also "Enable our configuration" below
- name: Create object config dir
  file:
    state: directory
    path: /etc/icinga2/conf-actual.d


# Urgh synchronize module doesn't support sudo.
# Use unprivileged user directory as staging area.
- name: 1/5 object config - create temp dir
  file:
    state: directory
    path: .ansible/role/icinga2/conf.d
  become: no

- name: 2/5 object config - sync to temp dir
  synchronize:
    delete: yes
    src: conf.d/
    dest: .ansible/role/icinga2/conf.d/
  check_mode: no  # run this command even in --check mode.  See 5/5
  become: no

# The following require privilege.
# However they also need to know where the un-escalated user was.
# This seems to work fine with ssh+sudo.
- name: 3/5 object config - diff icinga2
  command: diff -r -q
             .ansible/role/icinga2/conf.d/ 
             /etc/icinga2/conf-actual.d/
  check_mode: no
  changed_when: False
  register: diff
  failed_when: diff.rc not in [0,1] or diff.stderr != ""
  
- name: 4/5 object config - sync to icinga2
  command: rsync -a --delete
             .ansible/role/icinga2/conf.d/ 
              /etc/icinga2/conf-actual.d
  when: diff.rc != 0
  notify: 'Test icinga2 and restart'

# "fix" check mode
- name: 5/5 object config - verify icinga2
  command: diff -r -q
             .ansible/role/icinga2/conf.d/ 
             /etc/icinga2/conf-actual.d/
  check_mode: no
  changed_when: False


- name: Enable our configuration (and disable the examples)
  lineinfile:
    path: /etc/icinga2/icinga2.conf
    state: present
    regexp: '^include_recursive "conf'
    line: 'include_recursive "conf-actual.d"'
  notify: 'Test icinga2 and restart'


- name: Ensure icinga2 is enabled
  service:
    name: icinga2
    enabled: yes
    state: started
