- name: Install icinga2
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - icinga2

    # check_dig is in monitoring-plugins-standard.
    # This is not pulled in automatically by icinga2.
    #
    # Note rpcbind is among the packages it recommendeds.
    # You might want to opt out of running rpcbind.
    # roles/sourcejedi.disable_unwanted_servers
    # can be used to mask it in advance.
    #
    - monitoring-plugins

# Note this role does not enable any "features", including the checker (?).
# The output features you want differ completely, between
# icinga2-classicui and the "modern" Icinga Web frontends.
# (Even the logs of old states are different plugins).


# We attempt in vain to mitigate dpkg prompts on upgrade.
# We leave the example conf.d/ alone and create our own.
# See also "Enable our configuration" below
- name: Create object config dir
  file:
    state: directory
    path: /etc/icinga2/conf-actual.d


# Urgh synchronize module doesn't support sudo.
# Use unprivileged user directory as staging area.
#
# Notice how this should work even if "~" includes a trailing space :-).
- name: Get temp directory
  shell: 'echo ~/.ansible/role/icinga2/conf.d'
  check_mode: no
  changed_when: False
  register: icinga2__echo_tmp
  become: no

- name: Get temp directory
  set_fact:
    icinga2__tmp: "{{ icinga2__echo_tmp.stdout | trim }}"


- name: 1/6 object config - create temp dir
  file:
    state: directory
    path: "{{ icinga2__tmp }}"
  become: no

# "fix" check mode
- name: 2/6 object config - check temp dir created
  command: "test -d {{ icinga2__tmp | quote }}"
  become: no
  check_mode: no
  changed_when: False

- name: 3/6 object config - sync to temp dir
  synchronize:
    delete: yes
    src: conf.d/
    dest: "{{ icinga2__tmp }}"
  check_mode: no  # run this command even in --check mode.  See 5/5
  become: no

# The following require privilege.
- name: 4/6 object config - diff icinga2
  command: diff -r -q
             {{ icinga2__tmp }}
             /etc/icinga2/conf-actual.d/
  check_mode: no
  changed_when: False
  register: diff
  failed_when: diff.rc not in [0,1] or diff.stderr != ""

- name: 5/6 object config - sync to icinga2
  command: rsync -a --delete
             {{ icinga2__tmp }}/
             /etc/icinga2/conf-actual.d
  when: diff.rc != 0
  notify: 'Test icinga2 and restart'

# "fix" check mode
- name: 6/6 object config - verify icinga2
  command: diff -r -q
             {{ icinga2__tmp }}
             /etc/icinga2/conf-actual.d/
  check_mode: no
  changed_when: False


- name: Enable our configuration (and disable the examples)
  lineinfile:
    dest: /etc/icinga2/icinga2.conf
    state: present
    regexp: '^include_recursive "conf'
    line: 'include_recursive "conf-actual.d"'
  notify: 'Test icinga2 and restart'


- name: Ensure icinga2 is enabled
  service:
    name: icinga2
    enabled: yes
    state: started
