#!/bin/sh
set -e

VER="$1"
if [ -z "$VER" ]; then
	echo "usage: $0 { jessie | stretch | unstable }"
	echo "(Debian stretch is the testing distribution)"
	exit 1
fi

cd "$(dirname "$0")"/../

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backup of $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos-apt/files/apt.conf.d /etc/apt
cp -rv roles/repos-apt/files/debian-"$VER".sources.list /etc/apt/sources.list

case "$DIST" in
jessie)
	echo
	echo 'Add jessie-backports repo (UK mirror)'
	cp -rv roles/repos-debian-jessie-backports/files/apt /etc
esac

echo
apt-get update

# apt installs (debconf) complains
apt-get -y install whiptail

case "$DIST" in
jessie)
	echo
	echo 'Install ansible from jessie-backports'
	apt-get -y install ansible/jessie-backports
	;;
*)	
	echo
	echo 'Install ansible'
	apt-get -y install ansible
esac

echo
echo 'Bootstrap complete!'
echo 'Remember to check for security updates at some point.'
echo 'You can run ansible.  Try starting with `ansible-playbook --check`.'
