#!/bin/sh
set -e

cd "$(dirname "$0")"/../playbooks/

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backing up $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos-debian-jessie/files/apt /etc

echo
echo 'Add jessie-backports repo (UK mirror)'
cp -rv roles/repos-debian-jessie-backports/files/apt /etc

echo
echo 'Install ansible from jessie-backports'
apt-get update
apt-get install -y ansible/jessie-backports

echo
echo 'Bootstrap complete!'
echo 'Now run ansible.  Try starting with `ansible-playbook --check`.'
echo 'You might also want to run `apt-get upgrade` afterwards.'
