#!/bin/sh
set -e

cd "$(dirname "$0")"/../playbooks/

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backing up $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos-debian-stretch/files/apt /etc

# Debian's etckeeper package sets itself up without any fuss
# (and they haven't messed up the defaults).
echo
echo 'Install etckeeper'
apt-get install etckeeper

echo
echo 'Install ansible'
apt-get update
apt-get install -y ansible

echo
echo 'Bootstrap complete!'
echo 'Now run ansible.  Try starting with `ansible-playbook --check`.'
echo 'You might also want to run `apt-get upgrade` afterwards.'
