#!/bin/sh
set -e

cd "$(dirname "$0")"/../playbooks/

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backing up $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos-debian-unstable/files/apt /etc

apt-get update

# Debian's etckeeper package sets itself up.
# They haven't messed up the defaults either.
# That said, roles/sourcejedi.etckeeper is useful
# to stop messages about setting user.email.
echo
echo 'Install etckeeper'
apt-mark hold rsync # rec by git, should be dropped in buster
apt-mark hold rename # rec by perl, should be dropped in buster

apt-get install -y etckeeper

apt-mark unhold rsync
apt-mark unhold rename


echo
echo 'Install ansible'
apt-get install -y ansible

echo
echo 'Bootstrap complete!'
echo 'Now run ansible.  Try starting with `ansible-playbook --check`.'
echo 'You might also want to run `apt-get upgrade` afterwards.'
