#!/bin/sh
set -e -o nounset

if [ $# -lt 1 ]; then
	echo "usage: $0 { stretch | buster | unstable }"
	exit 1
fi
VER="$1"

cd "$(dirname "$0")"/../

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backup of $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos_apt/files/apt.conf.d /etc/apt
cp -rv roles/repos_apt/files/debian-"$VER".sources.list /etc/apt/sources.list

#case "$VER" in
#jessie)
#	echo
#	echo 'Add jessie-backports repo (UK mirror)'
#	cp -rv roles.old/repos-debian-jessie-backports/files/apt /etc
#esac

echo
apt-get update

# apt installs (debconf) complains
apt-get -y install whiptail

case "$VER" in
#jessie)
#	echo
#	echo 'Install ansible from jessie-backports'
#	apt-get -y install ansible/jessie-backports
#	;;
*)	
	echo
	echo 'Install ansible'
	apt-get -y install ansible
esac

# python3-apt is available at least starting from Debian Jessie.
# python-apt is removed in Debian Buster (and ansible uses python3).
echo
echo 'Install requirements for ansible target'
apt-get -y install python3-apt python-apt || apt-get -y install python3-apt

echo
echo 'Bootstrap complete!'
echo 'Remember to check for security updates at some point.'
echo 'You can run ansible.  Try starting with `ansible-playbook --check`.'
