#!/bin/sh
set -e -o nounset

cd "$(dirname "$0")"/../

SRC=/etc/yum.repos.d
DST=/etc/orig-yum.repos.d
echo "Backing up $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Fedora repos using local cache'
cp -rv roles/repos-fedora/files/yum.repos.d /etc

echo
echo 'Install ansible and requirements for ansible target'

# python2-dnf - required on dnf systems (and ansible does not automatically install it)
# When ansible package switches to python3, this will not be necessary
# (but it probably will not cause an immediate problem).
# python3-dnf is included in Fedora as a core requirement of its versison of dnf.
#
# libselinux-python - required to run ansible file tasks, when selinux is enabled
PKG_LIST="ansible python2-dnf libselinux-python"
dnf install -y $PKG_LIST

echo
echo 'Bootstrap complete!'
echo 'Now run ansible.  Try starting with `ansible-playbook --list-tasks`.'
echo 'You might also want to run `pkcon update` afterwards.'
