#!/bin/sh
set -e

cd "$(dirname "$0")"/../playbooks/

SRC=/etc/yum.repos.d
DST=/etc/orig-yum.repos.d
echo "Backing up $SRC to $DST, if it does not already exist"
if [ ! -e "DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Fedora repos using local cache'
cp -rv roles/repos-fedora/files/yum.repos.d /etc

echo
echo 'Install ansible, and requirements for ansible target, from Fedora repos'

# libselinux-python - required to run ansible file tasks, when selinux is enabled
PKG_LIST="ansible libselinux-python"
dnf install -y $PKG_LIST

echo
echo 'Bootstrap complete!'
echo 'Now run ansible.  Try starting with `ansible-playbook --list-tasks`.'
echo 'You might also want to run `pkcon update` afterwards.'
