#!/bin/sh
set -e -o nounset

cd "$(dirname "$0")"/../

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backup of $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos-apt/files/apt.conf.d /etc/apt
cp -rv roles/repos-apt/files/ubuntu-xenial.sources.list /etc/apt/sources.list

echo
apt-get update

# apt installs (debconf) complains
apt-get -y install whiptail

# Recommended by ansible, for the latest release version.
# Ubuntu's ansible package is in universe,
# and there was no obvious sign of security updates.
echo
echo 'Add ansible PPA'
apt-get install -y software-properties-common
add-apt-repository -y ppa:ansible/ansible
apt-get update

echo
echo 'Install ansible'
apt-get -y install ansible

# python-apt / python3-apt
# At some point Ansible packages will switch to python3.
# python3-apt is available at least starting from Debian Jessie.
echo
echo 'Install requirements for ansible target'
apt-get -y install python-apt python3-apt

echo
echo 'Bootstrap complete!'
echo 'Remember to check for security updates at some point.'
echo 'Now run ansible.  Try starting with `ansible-playbook --check`.'
