#!/bin/sh
set -e -o nounset

cd "$(dirname "$0")"/../

SRC=/etc/apt
DST=/etc/orig.apt
echo "Backup of $SRC to $DST, if it does not already exist"
if [ ! -e "$DST" ]; then
	cp -av "$SRC" "$DST"
fi

echo
echo 'Configure Debian repos using local cache'
cp -rv roles/repos_apt/files/apt.conf.d /etc/apt
cp -rv roles/repos_apt/files/ubuntu-jammy.sources.list /etc/apt/sources.list

echo
apt-get update

# apt installs (debconf) complains
apt-get -y install whiptail

echo
echo 'Install ansible'
apt-get -y install ansible

echo
echo 'Install requirements for ansible target'
apt-get -y install python3-apt

echo
echo 'Bootstrap complete!'
echo 'Remember to check for security updates at some point.'
echo 'Now run ansible.  Try starting with `ansible-playbook --check`.'
