users:
 - name: alan-sysop
   full_name: Alan Jenkins (system admin)
   admin: True

 - name: alan
   full_name: Alan Jenkins

# We can do this the hard way, or the easy way.
alan_servers__admins:
 - alan-sysop

wireshark__users: "{{ alan_servers__admins }}"
