# ROLE NOT COMPLETED
# Missing:
# * creation of BUP_DIR's (atomically in mktemp -d ?)
# * config variables for backed up directories?

- name: Install bup, par2, cron
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bup
    - par2
    - cron

# This directory is visible without sudo.
#
# Also it's supposed to be on a separate disk.
# We require the admin to set it up first.

- name: Check for /data/backup/
  file:
    path: /data/backup/

# This directory is for root only

- name: Create /data/backup/bup
  file:
    path: /data/backup/borg
    mode: 0700
    state: directory

- name: Install cron job for bup
  copy:
    src: cron.daily/local-bup
    dest: /etc/cron.daily/{{ daily_bup__cron_prefix }}local-bup
    mode: a+x
