# DRAFT ROLE
# Missing:
# * config variables for backed up directories
# * atomic creation of BUP_DIR, in mktemp -d

- name: Install bup, par2, cron
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - bup
    - par2
    - cron

- name: Install cron job for bup
  copy:
    src: cron.daily/local-bup
    dest: /etc/cron.daily/{{ daily_bup__cron_prefix }}local-bup
    mode: a+x
