- name: Check OS family is Debian
  assert:
    that: "ansible_os_family == 'Debian'"

- name: Configure apt to use local caching proxy
  copy:
    src: apt.conf.d/02proxy
    dest: /etc/apt/apt.conf.d/
  register: proxy

- name: Configure apt to use UK mirror
  copy:
    src: '{{ repos_apt }}.sources.list'
    dest: /etc/apt/sources.list
  register: sources

# This test is slow, only bother when changed.
# (In which case, the next use of apt would have had to do it anyway).
- name: Test "apt-get update"
  command: apt-get update
  when: proxy.changed or sources.changed
  register: update
  failed_when: update.rc != 0 or update.stderr
  args:
    warn: no  # Can't use apt module.  It doesn't detect unreachable repos.
