- name: install apt-cacher-ng
  package: name=apt-cacher-ng state=present


# `lineinfile` is a hack.
# But, we only want to change a couple features.
# Avoid writing the whole file for now.
#
# Upstream examples are commented as e.g. "# ReportPage:".
# We can toggle between "ReportPage: " and "#ReportPage:" without collisions.


# I end up toggling the following choice manually
# depending on whether I'm feeling paranoid
# or wanting to check bandwidth or disk space.
#
# Note, if you disable the control page, then
# `/etc/cron.daily/apt-cacher-ng` will fail, so
# you probably want to `chmod a-x` that as well.

# ... of course this has the problem of not taking effect
# before apt-cacher-ng has already been started... 
#
- name: Disable control page
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(#?)ReportPage:'
    line: '#ReportPage: acng-report.html # non-essential, disabled for security'
  notify: [ 'Restart apt-cacher-ng' ]

#- name: SENSITIVE AREAS ARE NOT RESTRICTED BY DEFAULT
  #debug:
    #msg: "Quote: The AdminAuth option can be used to restrict access to sensitive areas"


- name: Disable web server (localhost:3142/acng-doc)
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(#?)LocalDirs:'
    line: '#LocalDirs: # not required, disabled as security precaution'
  notify: [ 'Restart apt-cacher-ng' ]


# apt-cacher-ng is flaky, sometimes I've used polipo instead.
# The following can be useful to transition from polipo.
#
#- name: Temporary upstream proxy
#  lineinfile:
#    dest: /etc/apt-cacher-ng/acng.conf
#    regexp: '^(#?)Proxy:'
#    line: 'Proxy: http://localhost:8123'
#  notify: [ 'Restart apt-cacher-ng' ]


# backends_ configuration files
#
- name: Set Debian repo to official Debian APT CDN service
  copy:
    content: |
      http://deb.debian.org/debian/
    dest: /etc/apt-cacher-ng/backends_debian
  notify: [ 'Restart apt-cacher-ng' ]

# ... then why did I not use the official one for Ubuntu as well?  Odd.
- name: Set Ubuntu repo to UK mirrorservice.org
  copy:
    content: |
      http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/
    dest: /etc/apt-cacher-ng/backends_ubuntu
  notify: [ 'Restart apt-cacher-ng' ]

# Fedora
#
# In previous experience, trying to use this as a proxy for Fedora
# was very frustrating.  New mirrors would keep popping up that were
# not in fedora_mirrors.  But using this as an origin server instead
# can work.

- name: Configure Fedora mapping
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^Remap-fedora:'
    line: 'Remap-fedora: /pub/fedora/linux ; file:backends_fedora # Fedora Linux'
  notify: [ 'Restart apt-cacher-ng' ]

# mirrorservice.org does not seem to work well here
# (incomplete metadata for minutes or tens of minutes,
#  and does not update on the same day, at least during releases).
#
# So far, I've seen mirror.ox.ac.uk have the same problem with incomplete
# metadata: 1 time.
#
- name: Set Fedora repo to Swansea University Computer Society (mirror.sucs.org)
  copy:
    content: |
      http://mirror.sucs.org/pub/linux/fedora
    dest: /etc/apt-cacher-ng/backends_fedora
  notify: [ 'Restart apt-cacher-ng' ]

- name: Update PfilePattern for Fedora
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(# )?PfilePatternEx:'
    line: 'PfilePatternEx: [a-f0-9]+-modules.yaml.gz|[a-f0-9]+-(primary|filelists|comps-[^.]*.[^.]*|updateinfo|prestodelta).xml(|.gz|.xz|.zck)  # fedora-modular.repo, and zchunk'
  notify: [ 'Restart apt-cacher-ng' ]

- name: ensure apt-cacher-ng is enabled
  service:
    name: apt-cacher-ng
    enabled: yes
    state: started
