- name: Install apt-cacher-ng
  package:
    name: apt-cacher-ng
    state: present

# `lineinfile` is a hack.
# But, we only want to change a couple features.
# Avoid writing the whole file for now.
#
# Upstream examples are commented as e.g. "# ReportPage:".
# We can toggle between "ReportPage: " and "#ReportPage:" without collisions.


# I end up toggling the following choice manually
# depending on whether I'm feeling paranoid
# or wanting to check bandwidth or disk space.
#
# Note, if you disable the control page, then
# `/etc/cron.daily/apt-cacher-ng` will fail, so
# you probably want to `chmod a-x` that as well.

# ... of course this has the problem of not taking effect
# before apt-cacher-ng has already been started... 
#
- name: Disable control page
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(#?)ReportPage:'
    line: '#ReportPage: acng-report.html # non-essential, disabled for security'
  notify: [ 'Restart apt-cacher-ng' ]

#- name: SENSITIVE AREAS ARE NOT RESTRICTED BY DEFAULT
  #debug:
    #msg: "Quote: The AdminAuth option can be used to restrict access to sensitive areas"


- name: Disable web server (localhost:3142/acng-doc)
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(#?)LocalDirs:'
    line: '#LocalDirs: # not required, disabled as security precaution'
  notify: [ 'Restart apt-cacher-ng' ]


# backends_ configuration files
#
- name: Set Debian repo to official Debian APT CDN service
  copy:
    content: |
      http://deb.debian.org/debian/
    dest: /etc/apt-cacher-ng/backends_debian
  notify: [ 'Restart apt-cacher-ng' ]

# ... then why did I not use the official one for Ubuntu as well?  Odd.
- name: Set Ubuntu repo to UK mirrorservice.org
  copy:
    content: |
      http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/
    dest: /etc/apt-cacher-ng/backends_ubuntu
  notify: [ 'Restart apt-cacher-ng' ]

- name: ensure apt-cacher-ng is enabled
  service:
    name: apt-cacher-ng
    enabled: yes
    state: started
