# DRAFT ROLE
# Missing:
# * config variables for backed up directories
# * atomic creation of BUP_DIR, in mktemp -d

- name: Ensure cron is installed
  package:
    name: cron
    state: installed

- name: Install cron job for bup
  copy:
    src: cron.daily/local-bup
    dest: /etc/cron.daily/{{ bup_daily__cron_prefix }}local-bup
    mode: a+x
