- name: Check if systemd would need to be installed
  package:
    name: systemd
    state: present
  check_mode: true
  register: systemd_simulated_install

- name: Require that systemd is already installed
  assert:
    that: not systemd_simulated_install.changed
    msg:
      This role will not convert your system to systemd.
      Please do so yourself before running this role.


- name: "[1/4] Check if apport-core-dump-handler needs removing"
  package:
    name: apport-core-dump-handler
    state: absent
  check_mode: true
  register: apport_core_dump_simulated_remove

- name: "[2/4] Install apport + systemd-coredump (Requires Ubuntu 24.04 or above)"
  package:
    name:
      - apport
      - systemd-coredump
    state: present
  when: apport_core_dump_simulated_remove.changed

- name: "[3/4] Check if apport-core-dump-handler is absent now"
  package:
    name: apport-core-dump-handler
    state: absent
  check_mode: true
  register: apport_core_dump_simulated_remove

# Deliberately break check_mode here.
# The next task will break it anyway, and that failure is more confusing.
- name: "[4/4] Require that apport-core-dump-handler is absent"
  assert:
    that: not apport_core_dump_simulated_remove.changed


# Check we will not break Ubuntu apport or equivalent.
#
# Use grep to find any foreign core handler.
# If there is none, grep will return 1 (failure),
# and we're ok to continue.
#
- name: Check that no other coredump handler is installed
  command:
    grep -v -E 'lib/systemd/systemd-coredump|^[^|]' /proc/sys/kernel/core_pattern
  register: core_pipe_and_is_not_systemd
  failed_when: core_pipe_and_is_not_systemd.rc != 1
  check_mode: no
  changed_when: False


# In Debian, systemd-coredump is not included in the "systemd" package.
# But on Fedora, there is no separate "systemd-coredump" package.
#
- name: Check for systemd-coredump
  stat:
    path: /lib/systemd/system/systemd-coredump.socket
  register: stat_systemd_coredump

- name: Install systemd-coredump as a distinct package
  package:
    name: systemd-coredump
    state: present
  when: not stat_systemd_coredump.stat.exists
