- name: install atop
  package:
    name: atop
    state: present

- name: enable atop service
  service:
    name: atop
    enabled: yes
    state: started


# https://bugzilla.redhat.com/show_bug.cgi?id=1571866

- name: Install fix for Fedora laptops
  copy:
    src: atop-pm.sh
    dest: /usr/lib/systemd/system-sleep/atop-pm.sh
  when: ansible_distribution == "Fedora"

- name: Enable fix for Fedora laptops
  file:
    path: /usr/lib/systemd/system-sleep/atop-pm.sh
    mode: a+rx
  when: ansible_distribution == "Fedora"
