google_chrome__yum_baseurl: "http://fedora-mirror.carrier.duckdns.org:3142/dl.google.com/linux/chrome/rpm/stable/"

# Update our master copy of the RPMFusion keys from the target system.
# This should sound worrying!  The role contains one fragile mitigation:
# the update is also reported as a failure.
rpmfusion__update_master_keys: yes

deb_mail_forward_root: 'alan-sysop, alan'

# roles/sourcejedi.disable_unwanted_servers
#
# I don't need any cups-browsed features.
# The role defaults don't disable it (yet).
disable_service_cups_browsed: yes

# roles/sourcejedi.cups
cups_disable_browsed: yes
