# smokeping.service just uses kill to reload, so it doesn't detect errors :-D.
- name: Reload smokeping
  command: /usr/sbin/smokeping --reload

- name: Restart apache2
  service:
    name: apache2
    state: restarted
