#!/bin/bash
# Find JPEG files and check them.

parallel() {
	command parallel --will-cite "$@"
}
#
# UNIX tradition expects that non-interactive commands stay quiet, dammit.
# This script was written for my own use.  If you find it useful, please read
# this script including the notice below from GNU parallel.  Let me know
# if you find a simpler alternative, which follows the UNIX tradition :-).
#
# Academic tradition requires you to cite works you base your article on.
# When using programs that use GNU Parallel to process data for publication
# please cite:
#
#   O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
#   ;login: The USENIX Magazine, February 2011:42-47.
#
# This helps funding further development; AND IT WON'T COST YOU A CENT.
# If you pay 10000 EUR you should feel free to use GNU Parallel without citing.


find "$@" \( -iname '*.jpg' -o -iname "*.jpeg" \) -print0 |
	parallel -0 -m jpeginfo --check 2>&1 |
	grep -v '\[OK\]$'
