- name: Query installed snaps
  shell: snap list | cut -f 1 -d " " | tail +2
  register: snaps
  failed_when: snaps.stderr != "" or snaps.rc != 0
  check_mode: no
  changed_when: False

- name: List unwanted Ubuntu Desktop snaps
  set_fact:
    ubuntu_gnome_remove_snaps:
      "{{ ubuntu_gnome_remove_snaps | select('in', snaps.stdout_lines) | list }}"

# Let's install first.  In case there's a problem, I'd prefer having two
# copies of e.g. gnome-logs over having no gnome-logs at all.
#
- name: Manually install apt packages to replace Ubuntu Desktop snaps
  package:
    name: "{{ ubuntu_gnome_remove_snaps }}"
    state: present

- name: Remove unwanted Ubuntu Desktop snaps
  command: "snap remove {{ item }}"
  with_items: "{{ ubuntu_gnome_remove_snaps }}"
