# An average user probably expects either Ubuntu's "No Open Ports"[1],
# and/or a firewall that behaves similar to Windows.
#
# This has not been upheld, so I recommend you configure a firewall.
# E.g. see sourcejedi.firewalld.  But you might additionally want to
# approximate "No Open Ports".  You can use this role to disable some
# common unwanted network services.
#
# Please note that Ubuntu's "No Open Ports" policy is dead.  It does
# not document the exception for cups-browsed (UDP port 631).  And the
# policy is no longer being applied to the media player app.[2]
#
# This role does not disable open ports in the media player, or other
# GUI apps.
#
# [1] https://wiki.ubuntu.com/SecurityTeam/Policies
# [2] https://bugs.launchpad.net/ubuntu/+source/rhythmbox/+bug/1771196


# Most people allow Avahi.  Ubuntu audited it for security at one point.
disable_service_avahi_daemon:


# cups-browsed: network printer discovery for CUPS.
# It has four independently switchable functions:
#
# 1. Query printers using modern MDNS, aka "Avahi" aka "Bonjour" aka
#    "Airprint".
#
# 2. Listen on UDP port 631 (ipp), for the legacy CUPS discovery protocol.
#
# 3. Query LDAP directory for printers.  This is not enabled by default.
#
# 4. Broadcast on UDP port 631 (ipp), for the legacy CUPS discovery protocol.
#    This is not enabled by default.
#
# Various instructions advise using this to discover network printers.[1]
# It seems the main reason is an issue with GTK.  The issue is that GTK
# can discover network printers on its own, but then fails to actually
# print to them.[2][3]  Assuming this issue is solved, most systems
# should be able to run without cups-browsed.
#
# [1] https://wiki.debian.org/QuickPrintQueuesCUPS#IPP_Printers
# [2] https://wiki.debian.org/CUPSDriverlessPrinting#CUPS_2.2.4_and_the_GTK_Print_Dialog
# [3] https://wiki.debian.org/CUPSPrintQueues#Printing_and_GTK_Applications
#
# Fedora Workstation 26-30 has this service disabled by default.
# It is enabled with default settings in Ubuntu and Debian.
# If you are not using it, you might want to disable it.
#
disable_service_cups_browsed:

# gdomap, part of gnustep-base-runtime. Pulled in e.g. by unar.
# Should be disabled, but there is a bug when upgrading to Debian 10.0.
#
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939119
#
disable_service_gdomap: yes

# minissdpd. Debian Desktop 8 and 9 (but not 10) install this by default,
# due to transmission-gtk.
disable_service_minissdpd: yes

# minidlna, pulled in by kipi-plugins, e.g. by digikam.
disable_service_minidlna: yes

# rpcbind installed by default in Debian 8, for NFSv3 client.
disable_service_rpcbind: yes

# nmbd: ancient network discovery in Samba.
# I.e. networking for Windows XP and below.
#
# Some Linux users may also use it as a way to access devices
# which only implement the legacy network discovery
# (because it was convenient for them to implement using Samba :-).
#
disable_service_nmbd: yes
