# I don't like updatedb running as a scheduled task.
# It's maybe less likely to be a problem than it used to be
# (mlocate optimization).  But I don't use it, so it's simplest to remove.

# 1/3) Query condition
- name: query  | is mlocate installed?
  # Get the list of package names, and look for "mlocate".
  # Make sure to detect errors.
  shell: |
    set -o errexit -o pipefail
    (rpm -qa --qf '%{NAME}\n' || exit 2) | grep ^mlocate$
  args:
    executable: /bin/bash
  register: mlocate_installed
  failed_when: mlocate_installed.rc not in [0, 1]
  check_mode: False
  changed_when: False

# 2/3) Run command task conditionally, to provide accurate "changed" status
- name: ensure | mlocate is not installed
  command: rpm -e mlocate
  when: mlocate_installed.rc == 0
  args:
    # Can't use ansible dnf module.  It would remove packages which depend
    # on mlocate, without prompting.
    warn: False

# 3/3) The condition must now hold.  This "fixes" ansible check mode.
- name: check  | mlocate is not installed
  # Get the list of package names, and look for "mlocate".
  # Make sure to detect errors.
  shell: |
    set -o errexit -o pipefail
    (rpm -qa --qf '%{NAME}\n' || exit 2) | grep ^mlocate$
  args:
    executable: /bin/bash
  register: mlocate_installed_check
  failed_when: mlocate_installed_check.rc != 1
  check_mode: False
  changed_when: False

- name: Remove unused packages
  dnf:
    autoremove: True
