#!/bin/sh

set -o nounset

# Note: bup generates progress messages when run in a tty,
# but when run from cron it will be silent unless there are errors.
#
# We rely on error messages being printed (as is usual).
# We don't try to set an exit status on errors
# Instead we continue and backup what we can.
#
# Tested on Debian 9 "stretch".
# The version of `bup save` in Debian 8 printed errors
# when it encountered sockets or pipes.

# Quick check
if ! ( mountpoint -q /data ||
       mountpoint -q /data/backup ||
       mountpoint -q /data/backup/bup )
then
	echo "Backup disk not mounted"
	exit 1
fi

cd /data/backup/bup || exit 1

for i in *; do
	[ -d "$i" ] || continue

	HOME_DIR=/home/"$i"
	export BUP_DIR="$PWD"/"$i"

	bup index "$HOME_DIR" \
		--exclude "$HOME_DIR"/.cache \
		--exclude "$HOME_DIR"/.mozilla
	bup save -q -n "$i" "$HOME_DIR"

	# Add bookmarkbackups from the firefox profile.
	# Firefox Sync doesn't e.g. protect against malice,
	# and I have a lot of bookmarks I want to keep.
	if [ -d "$HOME_DIR"/.mozilla ]; then
		bup index "$HOME_DIR"/.mozilla/firefox/*/bookmarkbackups
		bup save -q -n "$i-bookmarkbackups" "$HOME_DIR"
	fi
done

# Disabled for parity - borgbackup test
#
# # Generate par2 redundancy.
# # Although this is a `bup fsck` command, it only runs checks
# # on the newly created packs that want par2 files creating.
# #
# # It doesn't look like using the --quick option actually helps.
# # par2 is very cpu-intensive anyway
# # (and verify-pack doesn't look to be very intensive, even in it's IO).
#
# for i in *; do
# 	[ -d "$i" ] || continue
# 	export BUP_DIR="$PWD"/"$i"
# 	bup fsck -g
# done
