#!/bin/bash

# This script has been simplified by assuming borgbackup 1.1 or above.

# Originally tested on Debian 9 "stretch", i.e. borgbackup-1.0.9

# This was taking about 3 minutes, at 40% CPU.
# While the self-report only shows it taking 6 seconds;
# no idea what that is supposed to mean :-(.
# (prune doesn't show any time, but that doesn't account for it)
#
# This is not due to a problem with the FUSE mounts;
# we bypass them.  I double-checked: the per-user dirs alone take 1:45.
# Without prune takes 1:20.
#
# I guess IO load can sometimes be because it forces uncached IO.
# But I wonder why it is doing so much work here, including the CPU...
# It is not chunking; the full chunking took a lot longer (~15 mins).
#
# The logs say two years previous, it managed to complete in 1 or 2
# minutes.
#
# I was thinking it is a function of the number of different snapshots.
#
# The log is a bit confusing, because it doesn't itemize borg_init()
# separately.  borg_init() takes over 10s e.g. on /home/sheena
# I fixed that part, so right now it takes less that 2 minutes :-).
# Acceptable for now.

set -o nounset

readonly BORG_REPOS_DIR=/data/backup/borg

# Quick check
if ! ( mountpoint -q /data ||
       mountpoint -q /data/backup ||
       mountpoint -q /data/backup/borg )
then
	echo "Backup disk not mounted"
	exit 1
fi


# Show details when run from a terminal (idea stolen from bup).
# Otherwise, only show errors.
if tty >/dev/null; then
	readonly BORG_PROGRESS="--progress"
	readonly BORG_STATS="--stats --info"
else
	readonly BORG_PROGRESS=
	readonly BORG_STATS=
fi

# Write a log to show the time taken
log() {
	echo -- "$@" >> /var/log/local-borgbackup
}
log_date() {
	log "$(date --rfc-3339=seconds)"
}

# Log the start timestamp
log_start() {
	log_date
}
log_cmd() {
	local err=0

	"$@" || err=$?

	log "$*" || err=1
	log_date || err=1  # log time of completion

	return $err
}


# If the borg repo does not exist, create it - atomically.
# If interrupted, just leaves a small randomly-named directory lying around
borg_init() {
	local BORG_REPO="$1" &&

	if [ ! -e "$BORG_REPO" ]; then
		T=$(mktemp --dry-run "$BORG_REPO".tmp.XXXXXX) &&
		borg init --encryption=none "$T" &&

		# Avoid a prompt about the repo having being relocated.
		borg config --cache "$T" previous_location "$BORG_REPO" &&

		mv "$T" "$BORG_REPO"
	fi
}

backup_home() {
	local HOME_DIR="$1" &&
	local BORG_REPO="$2" &&

	borg_init "$BORG_REPO" &&

	export BORG_REPO &&

	# Exclusions:
	#
	# Firefox profile tends to churn a whole lot (but see below).
	#
	# Thunderbird has an index for searching messages, which shows up.
	# This is due to the size of the blocks borg uses (megabytes?),
	# although enabling compression helps a bit.
	# We're allowed to drop the index - it will be rebuilt.
	#
	# On Debian, there may be an icedove profile which is half-migrated
	# to thunderbird, but still uses the old location.
	#
	# Nowadays GNOME logs activity and indexes it, that shows up as well.
	#
	log_cmd borg create '::{now}' "$HOME_DIR" \
		$BORG_PROGRESS $BORG_STATS \
		-C lz4 \
		--one-file-system \
		--exclude "$HOME_DIR"/.cache \
		--exclude "$HOME_DIR"/.mozilla/firefox \
		--exclude "$HOME_DIR"/.thunderbird/*/global-messages-db.sqlite \
		--exclude "$HOME_DIR"/.icedove/*/global-messages-db.sqlite \
		--exclude "$HOME_DIR"/.local/share/zeitgeist/fts.index \
		--exclude "$HOME_DIR"/.local/share/tracker &&

	# Prune old backups to save space
	log_cmd borg prune $BORG_STATS \
		--keep-daily 21 --keep-weekly 6 \
		--keep-monthly 12 --keep-yearly -1
}

# Save bookmarkbackups from the firefox profile.
# Firefox Sync doesn't e.g. protect against malice,
# and I have a lot of bookmarks I want to keep.
backup_firefox_bookmarks() {
	local HOME_DIR="$1" &&
	local BORG_REPO="$2".firefox-bookmarks &&
	export BORG_REPO &&

	if [ ! -d "$HOME_DIR"/.mozilla ]; then
		return 0
	fi &&

	borg_init "$BORG_REPO" &&

	log_cmd borg create $BORG_PROGRESS $BORG_STATS '::{now}' \
		"$HOME_DIR"/.mozilla/firefox/*/bookmarkbackups &&

	log_cmd borg prune $BORG_STATS \
		--keep-daily 21 --keep-weekly 6 \
		--keep-monthly 12 --keep-yearly -1
}

# Note if any one backup step fails, we keep going.
# However an error should be printed, which works well for the cron job case.
# Also make sure to point out if there was an error (like rsync does :).
backup() {
	local err=0

	backup_home "$1" "$2" ||
		err=1
	backup_firefox_bookmarks "$1" "$2" ||
		err=1

	return $err
}

main() {
	local err=0

	log_start || return

	for i in mike sheena; do
		backup "/home/$i" "$BORG_REPOS_DIR/$i" ||
			err=1
	done

	backup /home/.shared-internal "$BORG_REPOS_DIR/jenkins-shared" ||
		err=1
	backup /home/.shared-separate-internal/Music "$BORG_REPOS_DIR/jenkins-music" ||
		err=1
	backup /home/.shared-separate-internal/Photos "$BORG_REPOS_DIR/jenkins-photos" ||
		err=1

	return $err
}

if ! main; then
	echo
	echo "WARNING: an error occurred.  Some or all files may not be backed up."
	exit 1
fi
