- name: Query - is snapd installed?
  script: scripts/dpkg-state snapd
  register: ubuntu_gnome_remove_snapd_already
  changed_when: False
  check_mode: False
  failed_when: ubuntu_gnome_remove_snapd_already.rc != 0 or
               ubuntu_gnome_remove_snapd_already.stdout|trim not in
                 ["not-installed", "config-files",
                  "unpacked", "half-installed", "half-configured",
                  "triggers-pending", "triggers-awaited", "installed"]

# Only try to remove snaps if snapd is installed :).
- include: ubuntu-gnome-remove-snaps.yml
  static: yes
  when: ubuntu_gnome_remove_snapd_already.stdout|trim not in
          ["not-installed", "config-files"]

- name: Remove snapd
  package:
    name: snapd
    state: absent
  when: ubuntu_gnome_remove_snapd
