- name: Create group
  group:
    name: jenkins-shared
    state: present

# insert comment here from sourcejedi.systemd-journal/README
- name: Add users to group
  user:
    name: "{{ item }}"

    append: yes
    groups: jenkins-shared
  with_items: "{{ jenkins_shared__users }}"


- name: Install bindfs
  package:
    name: bindfs
    state: present

# "You cannot use 'static' on an include with a loop." -- ansible 2.2.1.0

- name: Configure shared directory /home/shared
  import_tasks: shared-dir.yml
  vars:
    shared_external: "/home/shared"
    shared_internal: "/home/.shared-internal"

- name: Configure shared directory /home/.shared-separate
  import_tasks: shared-dir.yml
  vars:
    shared_external: "/home/.shared-separate"
    shared_internal: "/home/.shared-separate-internal"

# These are directories which are backed up in seperate archives from
# the rest of the shared files.
- name: Create separate shared directories (internal)
  file:
    dest: "/home/.shared-separate/{{ item }}"
    state: directory
    group: jenkins-shared
  with_items:
    - Photos
    - Music

- name: Create separate shared directories (visible links)
  file:
    path: "/home/shared/{{ item }}"
    state: link
    src: "../.shared-separate/{{ item }}"
  with_items:
    - Photos
    - Music

- name: Warn that extra files in .shared-separate will not be backed up.
  copy:
    src: dot-shared-separate/DO_NOT_PUT_EXTRA_FILES_OR_DIRECTORIES_HERE.txt
    dest: /home/.shared-separate/
    mode: a+r
#
# I notice xdg-style trash directories might be created at this
# top-level - and hence will not be backed up.  But I can accept this.
