- name: bfq=y | GRUB kernel option - scsi_mod.use_blk_mq=y
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="\s*((?!.*\b(scsi_mod.use_blk_mq=y)\b).*?)\s*"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 scsi_mod.use_blk_mq=y"'
  register:
    scsi_mod
  when: bfq

# "It may be beneficial to set dm_mod.use_blk_mq=y if the
#  underlying SCSI devices are also using blk-mq, as doing so
#  reduces locking overhead at the DM layer."
# Note LVM is implemented using DM.
- name: bfq=y | GRUB kernel option - dm_mod.use_blk_mq=y
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="\s*((?!.*\b(dm_mod.use_blk_mq=y)\b).*?)\s*"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 dm_mod.use_blk_mq=y"'
  register:
    dm_mod
  when: bfq

- name: bfq=n | GRUB kernel option - dm_mod.use_blk_mq=y
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="\s*(.*?)\s*\b(dm_mod.use_blk_mq=y)\b\s*(.*?)\s*"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 \3"'
  register:
    dm_mod
  when: not bfq

- name: bfq=n | GRUB kernel option - scsi_mod.use_blk_mq=y
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="\s*(.*?)\s*\b(scsi_mod.use_blk_mq=y)\b\s*(.*?)\s*"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 \3"'
  register:
    scsi_mod
  when: not bfq

- name: bfq=? | Update GRUB (EFI)
  shell: |
    if [ -d /boot/efi/ ]; then
      grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
    fi
  when: scsi_mod.changed or dm_mod.changed

- name: bfq=? | Update GRUB (BIOS)
  shell: |
    if [ -d /boot/grub2 ]; then
      grub2-mkconfig -o /boot/grub2/grub.cfg
    fi
  when: scsi_mod.changed or dm_mod.changed

# Not needed for DM, because it doesn't use a separate IO scheduler.
- name: bfq=y | Udev rule to configure SCSI with BFQ
  copy:
     dest: /etc/udev/rules.d/
     src: 99-local-io-scheduler.rules
  register: udev
  when: bfq

- name: bfq=n | Udev rule to configure SCSI with BFQ
  file:
    path: /etc/udev/rules.d/99-local-io-scheduler.rules
    state: absent
  register: udev
  when: not bfq
