# Remediate config first. Otherwise bad config can stop install.
- name: configure smokeping Targets and Alerts
  copy:
    src: "{{ item }}"
    dest: /etc/smokeping/config.d/
  notify:
    - Reload smokeping
    #
    # Restart smokeping.cgi (fcgid).
    # It's crude, but there's no better alternative with this stack.
    - Restart apache2
  with_items:
    - smokeping/config.d/Targets
    - smokeping/config.d/Alerts

- name: install smokeping, apache2, apache2 fastcgi
  package:
    name:
      - apache2
      - libapache2-mod-fcgid
      - smokeping
    state: present

# smokeping in jessie does not provide a new-style apache conf drop-in
- name: create configuration in apache2
  copy:
    src: apache2.conf
    dest: /etc/apache2/conf-available/smokeping.conf
  notify: Restart apache2

- name: enable configuration in apache2
  file:
    state: link
    path: /etc/apache2/conf-enabled/smokeping.conf
    src: ../conf-available/smokeping.conf
  notify: Restart apache2

- name: enable fastcgi module in apache2
  apache2_module:
    name: fcgid
    state: present
  notify: Restart apache2

# This happens at install time for Debian packages, but I also allow
# for the possibility that the admin disabled a service temporarily.
- name: enable and start smokeping
  service:
    name: smokeping
    enabled: yes
    state: started

- name: enable and start apache2
  service:
    name: apache2
    enabled: yes
    state: started

# Later roles may add more drop-in configs. Fail fast.
# Note reloading will error if the service has not been started.
- name: apply modified configs, if any
  meta: flush_handlers
