- name: Install bindfs
  package:
    name: bindfs
    state: present

- name: Create directory
  file:
    state: directory
    path: /home/jenkins-photos

# Let's take great care in fstab.
# 1. Use nofail option, so we can still boot without bindfs.
# 2. Try not to overwrite an existing line?
#
- name: Create entry in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/home/jenkins-photos[ \t]+/home/jenkins-photos[ \t]+fuse.bindfs([ \t]*|$)'
    line: '/home/jenkins-photos /home/jenkins-photos fuse.bindfs nofail,allow_other,force-group=jenkins-photos,perms=g+wX'
  register: jenkins_photos_fstab

- name: Restart mount unit if changed
  systemd:
    daemon_reload: yes  # uhh.
    # use systemctl do-what-I-mean,
    # this avoids manually escaping '-' characters in the path.
    name: /home/jenkins-photos
    state: restarted
  register: jenkins_photos_mount
  when: jenkins_photos_fstab|changed
  ignore_errors: yes

# 1. Some versions of systemd did not log mount errors :-(.
# 2. `systemctl start` error message suggests commands which use the
#    strange escaped unit name.
# 3. Testing with `mount /home/jenkins-photos` will fail unless you
#    have fuse-3.2.2 or higher - it chokes on the "nofail" option.
- name: Check mount unit success
  assert:
    that: not jenkins_photos_mount|failed
    msg: "Check `systemctl status /home/jenkins-photos`.  In case systemd does not log the error message, please manually run the command shown in ExecMount="

# This task is not idempotent: it will not apply changed options.
- name: Ensure mount unit is started
  systemd:
    # use systemctl do-what-I-mean,
    # this avoids manually escaping '-' characters in the path.
    name: /home/jenkins-photos
    state: started
  ignore_errors: yes
  register: jenkins_photos_mount

- name: Check mount unit success
  assert:
    that: not jenkins_photos_mount|failed
    msg: "Check `systemctl status /home/jenkins-photos`.  In case systemd does not log the error message, please manually run the command shown in ExecMount="

