- name: Check OS is Fedora
  assert:
    that: ansible_distribution == 'Fedora'

- name: Configure Fedora repos using local cache
  copy: src=yum.repos.d/ dest=/etc/yum.repos.d/
  register: repos

# This test is slow, only bother when changed.
# (In which case, the next use of dnf would probably have had to do this anyway).
# Do not defer this, as other roles may add drop-in configs.
- name: Test "dnf check-update"
  when: repos.changed
  command: dnf \
           --disablerepo="*" --enablerepo=fedora --enablerepo=updates
           --refresh check-update
  register: dnf_check_update
  # "exit code will be 100 when there are updates available and a list of the
  #  updates will be printed, 0 if not and 1 if an error occurs."
  failed_when: dnf_check_update.rc not in [0, 100]
  args:
    warn: no  # can't use ansible dnf module, it does not implement this
