# If we don't have the required python interpreter,
# use the raw module to install it.
# Then we shouldn't need to use the raw module any more.

- name: Check connection with ansible raw module
  raw: 'true'
  changed_when: False  # no change
  check_mode: no  # run this non-check module even in --check mode

# For science :).
# May also detect if command interpreter is not a unix shell.
- name: Check command interpreter can return failure
  raw: 'false'
  register: raw_false
  failed_when: raw_false.rc != 1
  changed_when: False
  check_mode: no


# Which python interpreter do we need to install?
# Fedora might only have python3 installed by default.
# Older distros may have Ansible that does not officially support python3.
# I don't claim the expression below is correct,
# only that it currently provides the correct result for me.
- name: Query if Ansible is configured to use python2 or python3
  set_fact:
    python2_or_python3:
      '{{ "python2" if ansible_python_interpreter is not defined else
          "python3" if ansible_python_interpreter == "/usr/bin/python3" else
          "null" }}'

# 1/3) Query condition
- name: query  | python installed, required by non-raw ansible modules
  raw: 'test -x /usr/bin/{{ python2_or_python3 }}'
  register: python_executable
  failed_when: False  # no fail.  rc is our result
  changed_when: False
  check_mode: no

# 2/3) Run raw task conditionally, to provide accurate "changed" status
- name: ensure | python installed, required by non-raw ansible modules
  when: python_executable.rc != 0
  # Try candidate install methods in sequence
  raw: |
    /usr/bin/dnf install -y {{ python2_or_python3 }} ||
    /usr/bin/apt-get install -y {{ python2_or_python3 }} ||
    /usr/bin/apt-get install -y {{ python2_or_python3 }} ||
    (echo "Failed to install required python package"; exit 1)
  changed_when: True  # always changes (unless failed)

# 3/3) The condition must now hold.  This "fixes" ansible check mode.
- name: check  | python installed, required by non-raw ansible modules
  raw: '/usr/bin/{{ python2_or_python3 }} -c "import sys; print (sys.version)"'
  changed_when: False
  check_mode: no


# Now non-raw modules should work.  Cross-check.
- name: Check ansible ping module works ok
  ping:
  check_mode: no


- name: Gather ansible facts
  setup:

# Now we should have ansible facts
