---
- include: main-tasks.yml
  tags: disable_unwanted_servers
  vars:
    network_services:
      - name: avahi-daemon
        disable: "{{ disable_service_avahi_daemon }}"

      - name: cups-browsed
        disable: "{{ disable_service_cups_browsed }}"

      - name: gdomap
        disable: "{{ disable_service_gdomap }}"

      - name: minidlna
        disable: "{{ disable_service_minidlna }}"

      - name: minissdpd
        disable: "{{ disable_service_minissdpd }}"

      - name: nmbd
        disable: "{{ disable_service_nmbd }}"

      - name: rpcbind
        disable: "{{ disable_service_rpcbind }}"

    error_services:
      "{{ network_services
              | rejectattr('disable', 'in', [True, False, None])
              | list }}"
        
    unwanted_services:
      "{{ network_services
              | selectattr('disable', 'equalto', True)
              | map(attribute='name')
              | list }}"

    wanted_services:
      "{{ network_services
              | selectattr('disable', 'equalto', False)
              | map(attribute='name')
              | list }}"
