- name: Check OS family is Debian
  assert:
    that: "ansible_os_family == 'Debian'"

- name: Configure apt proxy
  template:
    src: apt.conf.d/02proxy.j2
    dest: /etc/apt/apt.conf.d/02proxy
  register: proxy

- name: Configure apt proxy autodetection
  package:
    name: squid-deb-proxy-client
    state: "{{ 'present' if repos_apt_autodetect_apt_proxy else 'absent' }}"

- name: Configure apt to use UK mirror
  copy:
    src: '{{ repos_apt }}.sources.list'
    dest: /etc/apt/sources.list
  register: sources

# This test is slow, only bother when changed.
# (In which case, the next use of apt would have had to do it anyway).
# Do not defer this, as other roles may add drop-in configs.
- name: Test "apt-get update"
  command: apt-get update
  when: proxy.changed or sources.changed
  register: update
  failed_when: update.rc != 0 or update.stderr != ""
  args:
    warn: no  # Can't use apt module.  It doesn't detect unreachable repos.
