users:
 - name: alan-sysop
   full_name: Alan Jenkins (system admin)
   admin: True

 - name: alan
   full_name: Alan Jenkins

# We can do this the hard way, or the easy way.
alan_servers__admins:
 - alan-sysop
 

# We don't assign the systemd-journal group in role/users,
# to avoid that mysteriously depending on roles/nspawn-on-debian
# (that's what installs systemd).
systemd_journal__users: "{{ alan_servers__admins }}"

wireshark__users: "{{ alan_servers__admins }}"
