- name: Install powertop
  package: name=powertop state=present

# powertop --auto-tune overrides the normal kernel defaults, to save power.
# It BREAKS your system.  You must test that you are happy with this
# and be prepared to debug any problems that show up later as a result.
# "powertop usb mouse" shows one example.

- name: Create powertop.service
  copy:
    src: powertop.service
    dest: /etc/systemd/system/

- name: Enable all powertop overrides
  service:
    name: powertop
    state: started
    enabled: yes

# My notes say ansible is pedantic and doesn't support service units
# which exit immediately.  This was a problem with the stock
# powertop.service.  However our unit has RemainAfterExit=yes.
