# Debian/sigh
# Don't want rpcbind running. But some packages recommend it
# (and then Debian will start it). Protect against this.
#
# For simple idempotence, just mask the service
# While we're here, handle Fedora by masking the socket, see
# https://unix.stackexchange.com/questions/369937/fedora-25-and-disabling-whatever-is-listening-on-port-111/369943#369943


# systemd module refuses to mask services which do not exist
- name: "Mask rpcbind.service"
  file:
    path: /etc/systemd/system/rpcbind.service
    state: link
    src: /dev/null

- name: "Mask rpcbind.socket"
  file:
    path: /etc/systemd/system/rpcbind.socket
    state: link
    src: /dev/null

# it seems happy to stop services which are masked though :)

- name: "Reload systemd"
  systemd:
    daemon_reload: yes

- name: "Stop rpcbind.service"
  systemd:
    name: rpcbind.service
    state: stopped

- name: "Stop rpcbind.socket"
  systemd:
    name: rpcbind.socket
    state: stopped
