# Ubuntu 22.04
- hosts: alan-laptop-2023
  roles:
    - sourcejedi.etckeeper

    # Useful to log memory/CPU usage per process (default 10 min snapshots).
    - sourcejedi.atop

    - sourcejedi.google_chrome

    - role: sourcejedi.firewalld
      firewalld__services:
        - dhcpv6-client
        - mdns
        - transmission-client

    - sourcejedi.disable_unwanted_servers
    - sourcejedi.cups

    - sourcejedi.libvirt_nss

    - element
