# Ubuntu 24.04

- hosts: alan-laptop-2023
  roles:
    - sourcejedi.etckeeper

    - sourcejedi.atop

    - role: sourcejedi.firewalld
      firewalld__services:
        - dhcpv6-client
        - mdns
        - transmission-client
    - sourcejedi.disable_unwanted_servers
    - sourcejedi.cups

    - flatpak
    - sourcejedi.google_chrome
    - element_desktop

    - sourcejedi.libvirt_nss

    - ansible_ubuntu_ppa

  tasks:
    - name: flatpak installs
      flatpak:
        name: "{{ item }}"
        state: present
      with_items:
        - org.keepassxc.KeePassXC
      tags: flatpak
