# X201 is retired from being primary workstation
# due to failing hardware
#
- hosts: alan-x201
  roles:
    - repos-fedora
    - sourcejedi.etckeeper

    - users
    - openssh-server

    # Thinkpad X201 seems perfectly happy with `powertop --auto-tune`.
    - powertop-full-override

    - packages-gui
    - packages-trash-cli

    - packages-dev-basics

    - { role: sourcejedi.rpmfusion-remove, repo: nonfree }
    - { role: sourcejedi.rpmfusion-remove, repo: free }
