- hosts: brick
  roles:
    - role: repos-apt
      repos_apt: debian-jessie
    - repos-debian-jessie-backports

    - sourcejedi.etckeeper

    - users
    - { role: sourcejedi.systemd-journal,
                         systemd_journal__remove_syslog_daemon: no }
    - openssh-server

    - sourcejedi.hdparm-noapm

    - packages-trash-cli

    - polipo

    # now handled by nspawn-debian-stretch,
    # because Debian stretch requires ACNG from stretch.
    #- apt-cacher-ng

    # catch syslogs from router
    - rsyslog-srv

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - debian-smokeping
    - icinga2
