- hosts: brick
  roles:
    - role: repos-apt
      repos_apt: debian-stretch

    - sourcejedi.etckeeper
    - remove-rpcbind
    - sourcejedi.hdparm-noapm
    - users
    - { role: sourcejedi.systemd-journal,
                         # see rsyslog below
                         systemd_journal__disable_syslog_daemon: no
      }

    - openssh-server

    - systemd-coredump
    - atop

    # Cough, bootstrapping problem.
    - apt-cacher-ng

    - remove-mlocate-on-deb
    - packages-trash-cli

    # catch syslogs from router
    - rsyslog

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - smokeping
    - icinga2
