- hosts: brick
  roles:
    - role: repos-apt
      repos_apt: debian-stretch

    - sourcejedi.etckeeper

    - users
    - { role: sourcejedi.systemd-journal,
                         # see rsyslog below
                         systemd_journal__disable_syslog_daemon: no
      }
    - openssh-server

    - sourcejedi.hdparm-noapm
    - systemd-coredump
    - atop

    - polipo
    - apt-cacher-ng

    - packages-trash-cli

    # catch syslogs from router
    - rsyslog

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - smokeping
    - icinga2
