- hosts: brick
  roles:
    - role: repos-apt
      repos_apt: debian-stretch

    - sourcejedi.etckeeper
    - users
    - { role: sourcejedi.systemd-journal,
                         # see rsyslog below
                         systemd_journal__disable_syslog_daemon: no
      }
    - systemd-coredump

    - openssh-server

    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh
       - https
       - syslog
      firewalld__ports:
       # apt-cacher-ng
       - protocol: tcp
         port: 3142

       # quassel irc (occasionally)
       - protocol: tcp
         port: 4242

    - remove-rpcbind

    - sourcejedi.hdparm-noapm

    - sourcejedi.atop

    # Cough, bootstrapping problem.
    - apt-cacher-ng

    - remove-mlocate-on-deb
    - packages-trash-cli
    - jpegcheck

    # catch syslogs from router
    - rsyslog

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - smokeping
    - icinga2
