- hosts: brick
  roles:
    - role: repos-apt
      repos_apt: debian-stretch

    - sourcejedi.etckeeper

    - users
    - { role: sourcejedi.systemd-journal,
                         systemd_journal__disable_syslog_daemon: no }
    - openssh-server

    - sourcejedi.hdparm-noapm

    - packages-trash-cli

    - polipo
    - apt-cacher-ng

    # catch syslogs from router
    - rsyslog-srv

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - debian-smokeping
    - icinga2
