- hosts: brick
  roles:
    - role: repos-apt
      repos_apt: debian-buster

    - sourcejedi.etckeeper
    - users
    - { role: sourcejedi.systemd-journal,
                         # see rsyslog below
                         #systemd_journal__disable_syslog_daemon: no
      }
    - systemd-coredump

    - openssh-server

    - sourcejedi.disable_unwanted_servers
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh
       - https
       #- syslog
      firewalld__ports:
       # apt-cacher-ng
       - protocol: tcp
         port: 3142

       # quassel irc (occasionally)
       - protocol: tcp
         port: 4242

    - sourcejedi.hdparm-noapm

    - sourcejedi.atop

    - packages-cli-basics
    - jpegcheck
    - remove-mlocate-on-deb

    # Cough, bootstrapping problem.
    - apt-cacher-ng

    # catch syslogs from router
    #- rsyslog

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - smokeping
    #- icinga2

    # Old-school "mail" used by
    # * icinga
    # * cron-apt - notify of updates!
    # * backup script mess! - uses at/cron
    # * smartd
    #
    - deb-mail
