- hosts: candy
  roles:
    - role: repos_apt
      repos_apt: ubuntu-focal
      repos_apt_autodetect_apt_proxy: yes

    - sourcejedi.etckeeper

    - users    
    - openssh-server

    # Add admin user(s) to journald group, and enable persistent journal.
    - sourcejedi.systemd-journal

    # Enable firewalld.
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh

    - sourcejedi.cups

    # Useful to log memory usage per process (default 10 min snapshots).
    - sourcejedi.disable_unwanted_servers

    - sourcejedi.cups
    - remove-mlocate-on-deb  # Remove updatedb task

    - sourcejedi.atop
    
    # FIXME: "suggested packages: thunderbird-gnome-support"
    - packages-gui

    - packages-cli-basics
    - debian_recommends

    - bfq

    - role: flatpak
      flatpak__remove_snapd: yes
  tasks:
    - name: flatpak installs
      flatpak:
          name: "{{ item }}"
          state: present
      with_items:
          - com.skype.Client
          - us.zoom.Zoom
      tags: flatpak
