# Additional playbooks:
# - candy-remove-unused.yml

- hosts: candy
  roles:
    - role: repos_apt
      repos_apt: ubuntu-focal
      repos_apt_autodetect_apt_proxy: yes

    - sourcejedi.etckeeper

    - users    
    - openssh-server

    # Add admin user(s) to journald group, and enable persistent journal.
    - sourcejedi.systemd_journal

    # Enable firewalld.
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh

    - sourcejedi.cups

    - sourcejedi.disable_unwanted_servers

    - sourcejedi.cups

    # Useful to log memory usage per process (default 10 min snapshots).
    - sourcejedi.atop

    - sourcejedi.google_chrome
    - firefox
    # no thunderbird. save disk space.

    - packages-cli-basics

    - bfq

    - role: flatpak
      flatpak__remove_snapd: yes
  tasks:
    - name: flatpak installs
      flatpak:
          name: "{{ item }}"
          state: present
      with_items:
          - com.skype.Client
          - us.zoom.Zoom
      tags: flatpak
