# See also: jenkins-pc.yml

- hosts: jenkins-laptop
  tasks:
    - name: "Install apps (apt)"
      package:
        name:
          - keepassxc
        state: present
      tags: apps

    - name: "Install Zoom (video conference) - Unofficial snap package"
      snap:
        name: zoom-client
        state: present
      tags: zoom
