# Init jenkins-desktop.
#
# Debian does not implement "No open ports" (aspirational ubuntu policy).
# I suggest *always* initializing systems on a firewalled network.
# (E.g. standard home router config.  Sucks if you don't have a router.)
# Once this role is run, a firewall will be installed, and will allow the SSH port.

# Additional playbooks:
# - jenkins-desktop-postfix.yml
# - jenkins-desktop-backup.yml

- hosts: drystone
  roles:
    - role: repos_apt
      repos_apt: ubuntu-focal
      repos_apt_autodetect_apt_proxy: yes

    - sourcejedi.etckeeper

    - users

    # FIXME needs rename to use underscores
    - sourcejedi.systemd-journal

    # ubuntu uses apport
    #- systemd-coredump

    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh

    - sourcejedi.disable_unwanted_servers

# FIXME - one-off error here, perhaps before the printer was automatically detected?
# (definitely no error after printer was manually added)
#
# RUNNING HANDLER [sourcejedi.cups : Change ErrorPolicy for any existing printers] ********************
#fatal: [drystone]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "lpstat: No destinations added.\n", "stderr_lines": ["lpstat: No destinations added."], "stdout": "", "stdout_lines": []}
    - sourcejedi.cups

    # Temporary while installed on spinny disk drive
    - sourcejedi.hdparm-noapm

    - sourcejedi.atop
    - smartd

    # TODO
    # Create backup tasks.
    # Make sure to mount /data/backup/ first, I guess :).
    #- { role: daily-borgbackup,
    #          daily_borgbackup__cron_prefix: '50-' }

    # Note - remote administration is not permitted on jenkins-desktop.
    # SSH may be used for other backups though.
    - openssh-server

    - jpegcheck
    - jenkins-photos

    - packages-cli-basics
    - packages-gui

    - bfq

    - role: flatpak
      flatpak__remove_snapd: yes

  tasks:
    - name: /00-README.txt
      copy:
        dest: /00-README.txt
        src: "{{ inventory_dir }}/files/jenkins-desktop/README-rootfs.txt"
      tags: jenkins-desktop

    - name: /home/00-README.txt
      copy:
        dest: /home/00-README.txt
        src: "{{ inventory_dir }}/files/jenkins-desktop/README-home.txt"
      tags: jenkins-desktop

    - name: /data/00-README.txt
      copy:
        dest: /data/00-README.txt
        src: "{{ inventory_dir }}/files/jenkins-desktop/README-data.txt"
      tags: jenkins-desktop

    - name: Install apps
      package:
        name:
          - digikam
          - gimp
          - xsane
        state: present
      tags: apps
