# Init jenkins-desktop.
#
# Ubuntu aspires to "No open ports".  Nevertheless:
# I suggest *always* initializing systems on a firewalled network.
# (E.g. standard home router config.  Sucks if you don't have a router.)
# Once this role is run, a firewall will be installed, and will allow the SSH port.

# Additional playbooks:
# - jenkins-desktop-postfix.yml
# - jenkins-desktop-backup.yml

- hosts: drystone
  roles:
    - role: repos_apt
      repos_apt: ubuntu-focal
      repos_apt_autodetect_apt_proxy: yes

    - sourcejedi.etckeeper

    - users
    - sourcejedi.systemd-journal
    - systemd-coredump

    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh

    - sourcejedi.disable_unwanted_servers
    - sourcejedi.cups
    - remove-mlocate-on-deb  # Remove updatedb task

    # Temporary while installed on spinny disk drive
    - sourcejedi.hdparm-noapm

    - sourcejedi.atop
    - smartd

    # Create backup tasks.
    # Make sure to mount /data/backup/ first, I guess :).
    - { role: daily-borgbackup,
              daily_borgbackup__cron_prefix: '50-' }

    # Note - remote administration is not permitted on jenkins-desktop.
    # SSH may be used for other backups though.
    - openssh-server

    - jpegcheck
    - jenkins-photos

    - packages-cli-basics
    - packages-gui

  tasks:
    - name: /00-README.txt
      copy:
        dest: /00-README.txt
        src: "{{ inventory_dir }}/files/jenkins-desktop/README-rootfs.txt"
      tags: jenkins-desktop

    - name: /home/00-README.txt
      copy:
        dest: /home/00-README.txt
        src: "{{ inventory_dir }}/files/jenkins-desktop/README-home.txt"
      tags: jenkins-desktop

    - name: /data/00-README.txt
      copy:
        dest: /data/00-README.txt
        src: "{{ inventory_dir }}/files/jenkins-desktop/README-data.txt"
      tags: jenkins-desktop
