---
- hosts: silo
  vars:
    postfix_compatibility_level: '2'
    postfix_inet_interfaces: 'loopback-only'
    postfix_aliases:
      - user: 'root'
        alias: 'alan-sysop'
    postfix_relayhost: 'smtp.gmail.com'
    postfix_relaytls: 'true'
    postfix_smtp_tls_security_level: 'secure'
    postfix_smtp_tls_mandatory_protocols: '>= TLSv1.2'
    postfix_smtp_tls_mandatory_ciphers: 'high'
    postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
  vars_files:
    - postfix_sasl_secrets.yml
  roles:
    - Oefenweb.postfix
