- hosts: silo
  roles:
    - role: repos-apt
      repos_apt: debian-buster

    - sourcejedi.etckeeper
    - users
    - { role: sourcejedi.systemd-journal,
                         # see rsyslog below
                         systemd_journal__disable_syslog_daemon: no
      }
    - systemd-coredump

    - openssh-server

    - sourcejedi.disable_unwanted_servers
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh
       - https
       - syslog
      firewalld__ports:
       # apt-cacher-ng
       - protocol: tcp
         port: 3142

    # TODO: more selective hdparm role at least for Debian.
    # hdparm.deb looks like it wised up now, yay!
    - sourcejedi.hdparm-noapm

    - sourcejedi.atop

    - packages-cli-basics
    - packages-dev-basics

    - jpegcheck
    - remove-mlocate-on-deb

    # Thinkpad X201 seems perfectly happy with `powertop --auto-tune`.
    - powertop-full-override

    # Cough, bootstrapping problem.
    - apt-cacher-ng

    # catch syslogs from router
    - rsyslog

    # Old-school "mail" used by
    # * icinga
    # * smokeping
    # * cron-apt - notify of updates!
    # * backup script mess! - uses at/cron
    # * smartd

    - smartd

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - icinga2
    - smokeping

    - debian_recommends
