# Additional playbooks:
# - silo-postfix.yml
# - jenkins-desktop-backup.yml

- hosts: silo
  roles:
    - role: repos_apt
      repos_apt: debian-buster
      # Cough, bootstrapping problem.
      repos_apt_proxy: 'http://localhost:3142'

    - sourcejedi.etckeeper
    - users
    - { role: sourcejedi.systemd-journal,
                         # see rsyslog below
                         systemd_journal__disable_syslog_daemon: no
      }
    - systemd-coredump

    - openssh-server

    - sourcejedi.disable_unwanted_servers
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh
       - https
       - syslog
      firewalld__ports:
       # apt-cacher-ng
       - protocol: tcp
         port: 3142

    # TODO: more selective hdparm role at least for Debian.
    # hdparm.deb looks like it wised up now, yay!
    - sourcejedi.hdparm-noapm

    - sourcejedi.atop

    - packages-cli-basics
    - packages-dev-basics

    - jpegcheck
    - remove-mlocate-on-deb

    # Thinkpad X201 seems perfectly happy with `powertop --auto-tune`.
    - powertop-full-override

    - apt-cacher-ng

    # catch syslogs from router
    - rsyslog

    - smartd

    - deb-apache
    - deb-apache-acl  # kept separate for easier testing
    - icinga2
    - smokeping

    - debian_recommends
