- hosts: test-vm-fedora
  roles:
    - repos-fedora
    - sourcejedi.etckeeper

    - users
    - sourcejedi.systemd_journal
    - openssh-server

    - sourcejedi.atop
    - remove-mlocate-on-fedora
    - packages-cli-basics
    - packages-dev-basics

    #
    # Roles which are not always used, or mostly used to test the role itself
    #

    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh

    #- sourcejedi.rpmfusion_free
    #- { role: sourcejedi.rpmfusion_remove, repo: "free" }

    #- sourcejedi.google_chrome
    #- sourcejedi.google_chrome_remove
