- hosts: test-vm-fedora
  roles:
    - repos-fedora
    - sourcejedi.etckeeper

    - users
    - sourcejedi.systemd-journal
    - openssh-server

    - sourcejedi.atop
    - remove-mlocate-on-fedora
    - packages-trash-cli
    - packages-dev-basics

    #- sourcejedi.rpmfusion-free
    #- { role: sourcejedi.rpmfusion-remove, repo: "free" }

    #- sourcejedi.google-chrome
    #- sourcejedi.google-chrome-remove
