- hosts: test-vm-debian
  roles:
    - repos-apt

    # used for ansible
    - role: repos-debian-jessie-backports
      when: repos_apt == 'debian-jessie'

    - sourcejedi.etckeeper
    - users
    - sourcejedi.systemd-journal

    - role: systemd-coredump
      when: ansible_distribution == "Debian"

    - sourcejedi.atop

    - openssh-server

    - packages-cli-basics
    - packages-dev-basics
    - sourcejedi.ccache

    # ubuntu1804.  Remember to update role if any other version is used.
    - role: ubuntu-gnome-remove-snaps
      ubuntu_gnome_remove_snapd: yes
      when: ansible_distribution == "Ubuntu"

    - sourcejedi.disable_unwanted_servers
    - remove-mlocate-on-deb

    #
    # Roles which are not always used, or mostly used to test the role itself
    #

    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - mdns
       - ssh
    - sourcejedi.cups

    # relied upon for daily-borgbackup and daily-rsync (cron mail).
    - deb-mail

    - packages-gui

    - jpegcheck

    - jenkins-photos

    - { role: daily-borgbackup,
              daily_borgbackup__cron_prefix: '50-' }

    ## Test using test-vm-debian9 as both the client and the server.
    - { role: daily-rsync,
              daily_rsync__cron_prefix: '60-' }
