- hosts: test-vm-debian
  roles:
    - repos-apt

    # used for ansible
    - role: repos-debian-jessie-backports
      when: repos_apt == 'debian-jessie'

    - sourcejedi.etckeeper
    - remove-rpcbind
    - users
    - sourcejedi.systemd-journal

    - role: systemd-coredump
      when: ansible_distribution == "Debian"

    - sourcejedi.atop

    - openssh-server

    - packages-trash-cli
    - packages-dev-basics

    - role: ubuntu-gnome-remove-snaps
      ubuntu_gnome_remove_snapd: yes
      when: ansible_distribution == "Ubuntu"

    - remove-mlocate-on-deb

    #
    # Roles which are not always used, or mostly used to test the role itself
    #

    # relied upon for daily-borgbackup and daily-rsync (cron mail).
    #- deb-mail

    #- packages-gui

    #- jpegcheck

    - jenkins-photos

    - { role: daily-borgbackup,
              daily_borgbackup__cron_prefix: '50-' }

    # Test using test-vm-debian9 as both the client and the server.
    - { role: daily-rsync,
              daily_rsync__cron_prefix: '60-' }
