- hosts: test-vm-debian
  roles:
    - role: repos_apt
      repos_apt_proxy: 'http://silo.carrier.duckdns.org:3142/'

    - sourcejedi.etckeeper
    - users
    - sourcejedi.systemd_journal

    - role: systemd-coredump
      when: ansible_distribution == "Debian"

    - sourcejedi.atop

    - openssh-server

    - sourcejedi.disable_unwanted_servers
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - ssh
       - https

    - packages-cli-basics
    - packages-dev-basics
    - sourcejedi.ccache

    #
    # Roles which are not always used, or mostly used to test the role itself
    #

    - sourcejedi.cups

    - deb-apache
    #- apt-cacher-ng

    # These might add a little network hassle to some systems,
    # so we disable them when not under test.
    #
    #- icinga2
    #- smokeping

    # relied upon for daily-rsync (cron mail).
    - role: Oefenweb.postfix
      postfix_compatibility_level: '2'
      postfix_inet_interfaces: 'loopback-only'
      postfix_aliases:
        # Redirect system mail to sysop user.
        - user: 'root'
          alias: 'alan-sysop'

    - packages-gui
    - sourcejedi.libvirt_nss

    - jpegcheck

    # fails?
    #- jenkins-photos

    # fills up disk??
    #- { role: daily-borgbackup,
    #          daily_borgbackup__cron_prefix: '50-' }

    ## Test using debian10-vm as both the client and the server.
    - { role: daily-rsync,
              daily_rsync__cron_prefix: '60-' }
