- hosts: test-vm-fedora
  roles:
    - repos-fedora
    - sourcejedi.etckeeper

    - users
    - sourcejedi.systemd-journal
    - openssh-server

    - packages-trash-cli
    - packages-dev-basics
    - remove-mlocate-on-fedora
