- hosts: test-vm-debian
  roles:
    - repos-apt

    # used for ansible
    - role: repos-debian-jessie-backports
      when: repos_apt == 'debian-jessie'

    - sourcejedi.etckeeper
    - remove-rpcbind
    - users
    - sourcejedi.systemd-journal

    - role: systemd-coredump
      when: ansible_distribution == "Debian"

    - sourcejedi.atop

    - openssh-server

    - packages-trash-cli
    - packages-dev-basics

    #- packages-gui
    - role: ubuntu-gnome-remove-snaps
      ubuntu_gnome_remove_snapd: yes
      when: ansible_distribution == "Ubuntu"

    - remove-mlocate-on-deb


    #- { role: daily-borgbackup,
    #          daily_borgbackup__cron_prefix: '50-' }

    #- { role: daily-rsync,
    #          daily_rsync__cron_prefix: '60-' }
