- hosts: test-vm-debian
  roles:
    - role: repos_apt
      repos_apt_proxy: 'http://silo.carrier.duckdns.org:3142/'

    - sourcejedi.etckeeper
    - users
    - sourcejedi.systemd_journal

    - role: systemd-coredump
      when: ansible_distribution == "Debian"

    - sourcejedi.atop

    - openssh-server

    - sourcejedi.disable_unwanted_servers
    - role: sourcejedi.firewalld
      firewalld__services:
       - dhcpv6-client
       - ssh

    - packages-cli-basics
    - packages-dev-basics
    - sourcejedi.ccache

    - remove-mlocate-on-deb

    # ubuntu1804.  Remember to update role if any other version is used.
    - role: ubuntu-gnome-remove-snaps
      ubuntu_gnome_remove_snapd: yes
      when: ansible_distribution == "Ubuntu"

    #
    # Roles which are not always used, or mostly used to test the role itself
    #

    - sourcejedi.cups

    - deb-apache
    - apt-cacher-ng

    # These might add a little network hassle to some systems,
    # so we disable them when not under test.
    #
    #- icinga2
    #- smokeping

    # relied upon for daily-borgbackup and daily-rsync (cron mail).
    - deb-mail

    - packages-gui
    - sourcejedi.libvirt_nss

    - jpegcheck

    - jenkins-photos

    - { role: daily-borgbackup,
              daily_borgbackup__cron_prefix: '50-' }

    ## Test using debian10-vm as both the client and the server.
    - { role: daily-rsync,
              daily_rsync__cron_prefix: '60-' }
