- hosts: test-vm-debian
  roles:
    - repos-apt
    - role: repos-debian-jessie-backports
      when: repos_apt == 'debian-jessie'

    - sourcejedi.etckeeper
    - remove-rpcbind
    - users
    - sourcejedi.systemd-journal

    - role: systemd-coredump
      when: ansible_distribution == "Debian"

    - sourcejedi.atop

    - openssh-server

    - packages-trash-cli
    - packages-dev-basics

    #- packages-gui

    - remove-mlocate-on-deb

    #- { role: daily-bup,
    #          daily_bup__cron_prefix: '50-' }

    #- { role: daily-borgbackup,
    #          daily_borgbackup__cron_prefix: '50-' }

    #- { role: daily-rsync,
    #          daily_rsync__cron_prefix: '60-' }
