- name: Install borgbackup, cron
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - borgbackup
    - cron

# Note - this role is not really configurable, to keep it simple
# and to avoid appearing more general than it is (just edit the script).
# __cron_prefix is a useful abstraction for me, however.

# directory is visible without sudo
- name: Create /data/backup/
  file:
    path: /data/backup

# contents is for root only
- name: Create /data/backup/borg
  file:
    path: /data/backup/borg
    mode: 0700

- name: Install cron job for borg
  copy:
    src: cron.daily/local-borgbackup
    dest: /etc/cron.daily/{{ daily_borgbackup__cron_prefix }}local-borgbackup
    mode: a+x
