# DRAFT ROLE see daily-bup

- name: Install borgbackup, cron
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - borgbackup
    - cron

# directory is visible without sudo
- name: Create /data/backup/
  file:
    path: /data/backup

# contents is for root only
- name: Create /data/backup/borg
  file:
    path: /data/backup/borg
    mode: 0600

- name: Install cron job for borg
  copy:
    src: cron.daily/local-borgbackup
    dest: /etc/cron.daily/{{ daily_borgbackup__cron_prefix }}local-borgbackup
    mode: a+x
