- name: Install unattended-upgrades
  package: name=unattended-upgrades state=present

- name: Configure unattended-upgrades
  copy:
    src: apt.conf.d
    dest: /etc/apt/

- name: Install needrestart to restart services automatically
  package: name=needrestart state=present

