# "Community-maintained" PPA.

- name: Add ansible Personal Package Archive (community maintained)
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present
    update_cache: false
  register: source

# This test is slow, only bother when changed.
# (In which case, the next use of apt would have had to do it anyway).
- name: Test "apt-get update"
  command: apt-get update
  when: source.changed
  register: update

- name: Show warnings from apt-get update
  debug:
    msg: "{{ update.stderr | d('') }}"
  when: update.stderr | d('')

# We make sure we get the PPA version, even if ansible was already installed.
- name: Install ansible from the PPA
  apt:
    name: ansible
    state: "{{ 'latest' if source.changed else 'present' }}"
