- name: Install exim4 and bsd-mailx
  package:
    name:
      - exim4
      - bsd-mailx
    state: present

- name: Redirect root mail
  lineinfile:
    path: /etc/aliases
    regexp: '^root:'

    # Note: variable must not contain newlines
    line: 'root: {{ deb_mail_forward_root }}'
