# This uses exim4 for handling "local" unix mail.  It sounds like exim4
# would not be so great if you want to recieve mail from the network.
#
# Postfix was designed to be more secure, and is the default in Ubuntu.
# I'm just being lazy here, so I don't have to disable port 25 in
# Postfix.

- name: Install exim4 and bsd-mailx
  package:
    name:
      - exim4
      - bsd-mailx
    state: present

- name: Redirect root mail
  lineinfile:
    dest: /etc/aliases
    regexp: '^root:'

    # Note: variable must not contain newlines
    line: 'root: {{ deb_mail_forward_root }}'
